spring:
  application:
    name: archref-ms

  data:
    mongodb:
      uri: mongodb://localhost:27017/archref-ms
      auto-index-creation: false

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}

  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

  cloud:
    stream:
      bindings:
        characterCreatedPublisher-out-0:
          destination: x-archref-character-created-event
        characterCreatedConsumer-in-0:
          destination: x-archref-character-created-event
          group: q-consumer-event

server:
  port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com:
      api: ${LOGGING_LEVEL_LSA:TRACE}

springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    health:
      sensitive: false
  health:
    db:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always

marvel-api:
  uri: https://gateway.marvel.com/v1/public/
  public-key: ${PUBLIC_KEY}
  private-key: ${PRIVATE_KEY}
  character-ids:
    - 1009491
    - 1009351
    - 1009368
    - 1009268
    - 1009268
    - 1010776
    - 1009257
    - 1009220
    - 1009261
    - 1010801
    - 1009338
    - 1010744
    - 1010734

